MODULES=()

# هذه هي الإعدادات الافتراضية لأداة mkinitcpio
BINARIES=()
FILES=()

# الـ HOOKS الأساسية مضاف عليها الـ kms لدعم كروت الشاشة بشكل أفضل
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck)
