# Low Latency & Gaming Performance Tweaks
# تقليل استخدام الـ Swap قدر الإمكان
vm.swappiness = 10
# تقليل استهلاك الـ Cache للتركيز على الأداء
vm.vfs_cache_pressure = 50
# تخصيص الذاكرة للعمليات الخلفية (لمونتاج 4K)
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
# تعطيل مراقب النظام لتقليل المقاطعات
kernel.nmi_watchdog = 0
# تفعيل TCP Fast Open لتحسين الشبكة للألعاب الأونلاين
net.ipv4.tcp_fastopen = 3
# خوارزمية BBR المتقدمة لتقليل البنج (Ping)
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
# تقليل Latency المعالج
kernel.sched_cfs_bandwidth_slice_us = 3000
